# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on: workflow_dispatch
jobs:
  backend-unit-tests:
    uses: rropen/reusable-workflows/.github/workflows/pytest.yml@main
    with:
      backend_directory: src/backend

  frontend-unit-tests:
    uses: rropen/reusable-workflows/.github/workflows/cypress_component_tests.yml@main
    with:
      frontend_directory: src/frontend
      
  docker-build:
    uses: rropen/reusable-workflows/.github/workflows/docker_build.yml@main
    with:
      dockerfile_directory: src/backend
      image: ghcr.io/rropen/mec_backend:latest
      registry: ghcr.io
    secrets:
      cr_username: ${{ secrets.GH_CR_USERNAME }}
      cr_PAT: ${{ secrets.CONTAINER_PAT }}
