name: Integration Test
on:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

  backend-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        
      - name: Make env file
        working-directory: ./src/backend
        run: cp .env.example .env
      
      - name: Build Docker Image
        working-directory: ./src
        run: docker-compose -f docker-compose.yml -f local-docker-compose.yml build

      - name: Run Docker Container
        run: docker-compose -f docker-compose.yml -f local-docker-compose.yml up -d backend

      - name: Check Running Containers
        run: docker ps

  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node:version: "14"

      - name: Install Yarn
        run: npm install

      - name: Install dependencies
        working-directory: src/frontend
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          headless: true
          working-directory: src/frontend
          start: yarn serve
          wait-on: "http://localhost:3000"
