name: Integration Test
on:
  push:
    branches:
      - 70-Github_Actions
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
            node:version: '14'

      - name: Install Yarn
        run: npm install
        
      - name: Install dependencies
        working-directory: src/frontend
        run: npm install
        

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          headless: true
          working-directory: src/frontend
          start: yarn serve
          wait-on: 'http://localhost:3000'
  # single:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: cypress-io/github-action@v2
  #       with:
  #         working-directory: src/frontend
  #         build: yarn run build
  #         start: yarn start
  #         

      
