name: Testing
# This workflow runs the unit test for the backend with pytest. 
# The component testing for the frontend with cypress
# Then the Integration Testing With Cypress

on: workflow_dispatch
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
     - name: Get yarn cache directory path
       id: yarn-cache-dir-path
       run: echo "::set-output name=dir::$(yarn cache dir)"
     - uses: actions/cache@v2
       id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
       with:
         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
         restore-keys: |
           ${{ runner.os }}-yarn-
     - name: Install project dependencies
       working-directory: src/frontend
       run: yarn
      
  # Runs Unit Tests w/ pytest
#   unit-tests:
#     runs-on: ubuntu-latest
#       container:
#           image: ghcr.io/rropen/mec_frontend:latest
#           credentials:
#             username: ${{ github.repository_owner }}
#             password: ${{ secrets.ITM007_CONTAINER_PAT }}
#           ports: 
#             - 3000:3000
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python 3.9
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9
          
#       - name: Install dependencies
#         working-directory: src/backend
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#       - name: Test with pytest
#         run: |
#           pytest

  # Run Component Tests
  # Runs Integration Tests w/ cypress
#   cypress-tests:
#     runs-on: ubuntu-latest
#     steps:
#         - name: Checkout Code
#           uses: actions/checkout@v2

#         - name: Setup Node
#           uses: actions/setup-node@v2
#           with:
#             working-directory: src/frontend
#             node:version: "14"
#             cache: 'yarn'
#         - run: yarn install --frozen-lockfile
#         - run: yarn cy

#         - name: Install Dependencies
#           working-directory: src/frontend
#           run: yarn install --frozen-lockfile

#         - name: Run Cypress Tests
#           working-directory: src/frontend
#           run: yarn cy
#           uses: cypress-io/github-action@v2
#           with:
#             install: false
#             browser: chrome
#             headless: true
#             working-directory: src/frontend
#             start: yarn serve
#             wait-on: "http://localhost:3000"

