name: Python application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Python
        uses: RojerGS/python-black-check@master
        with:
          line-length: "88"
          path: "./src/backend"
          include: "apps"
          exclude: "(/*.html|/*.mo|/*.po|/*.png|/*.rst)"
